//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NgCmsBackend
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRoute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblRoute()
        {
            this.tblContent = new HashSet<tblContent>();
            this.tblRoute1 = new HashSet<tblRoute>();
        }
    
        public int RouteId { get; set; }
        public string Path { get; set; }
        public System.Guid Guid { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
        public Nullable<int> ParentRouteId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblContent> tblContent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRoute> tblRoute1 { get; set; }
        public virtual tblRoute tblRoute2 { get; set; }
    }
}
